[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "habit-tracker"
version = "0.1.0"
dependencies = ["questionary"]

[tool.setuptools.packages.find]
where = ["src"]